name: Deploy to Azure VM1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
        script: |
          cd ~/flask-app
          git pull origin main
          pip3 install -r requirements.txt
          pkill gunicorn || true
          nohup gunicorn --bind 0.0.0.0:8000 app:app &
