name: Deploy to Azure VM3

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run flask-app
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@4.174.129.246 << 'EOF'
          cd /home/azureuser/flask-app
          git pull origin main
          # If using virtualenv, activate it here
          # source venv/bin/activate
          # Restart your Flask app or services here, example:
          pkill -f "python3 app.py"
          nohup python3 app.py > app.log 2>&1 &
        EOF
